### ISSUE TITLE
UART Spannung von Air530 überprüfen

### ISSUE THREAD

**Issue by LMueller-gsVision** [niklasvkr/Insect-ScannerRev2.0#4]
Raspberry pi zero UART ist CMOS/3.3V, Air530 sieht nach TTL/5V aus. Falls Air530 tatsächlich nur TTL Level hat brauchen wir auf TX und RX noch jeweils einen [Level Shifter](https://www.digikey.de/en/blog/logic-level-shifting-basics)

**Comment by niklasvkr** [comment]
Es scheint, dass das Air530 sowohl mit 5V als auch mit 3.3V betrieben werden kann. Die UART-Pegel passen sich entsprechend an die Betriebsspannung an. Sollte aber vor Bestellung der Platinen an Air530 nochmal getestet werden.
